### ISSUE TITLE
Orden de los embeddings

### ISSUE THREAD

**Issue by jgmontoya** [uchile-nlp/spanish-word-embeddings#7]
Hola,

Los vectores se encuentran ordenados por frecuencia?

Esto es útil para que al hacer por ejemplo:

```python
wordvectors_file_vec = 'fasttext-sbwc.3.6.e20.vec'
num_of_vectors = 50000
wordvectors = KeyedVectors.load_word2vec_format(wordvectors_file_vec, limit=num_of_vectors)
```

Los (por ejemplo) 50.000 vectores que se carguen sean los más frecuentes (y por ende posiblemente los más relevantes).

Saludos!

**Comment by josecannete** [comment]
Hola @jgmontoya,

Los primeros, entrenados en SUC con FastText, están en orden decreciente de frecuencia.

Saludos!

**Comment by jgmontoya** [comment]
Bueno saberlo, gracias!
